apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  finalizers:
    - tektonconfigs.operator.tekton.dev
  labels:
    operator.tekton.dev/release-version: v0.77.0
  name: config
spec:
  addon: {}
  chain:
    artifacts.oci.format: simplesigning
    artifacts.oci.storage: oci
    artifacts.pipelinerun.format: in-toto
    artifacts.pipelinerun.storage: oci
    artifacts.taskrun.format: in-toto
    artifacts.taskrun.storage: oci
    disabled: false
    options: {}
    performance:
      disable-ha: false
  config: {}
  dashboard:
    options: {}
    readonly: false
  hub:
    options: {}
  pipeline:
    await-sidecar-readiness: true
    coschedule: workspaces
    disable-creds-init: false
    enable-api-fields: beta
    enable-bundles-resolver: true
    enable-cel-in-whenexpression: false
    enable-cluster-resolver: true
    enable-custom-tasks: true
    enable-git-resolver: true
    enable-hub-resolver: true
    enable-param-enum: false
    enable-provenance-in-status: true
    enable-step-actions: true
    enforce-nonfalsifiability: none
    keep-pod-on-cancel: false
    max-result-size: 4096
    metrics.count.enable-reason: false
    metrics.pipelinerun.duration-type: histogram
    metrics.pipelinerun.level: pipeline
    metrics.taskrun.duration-type: histogram
    metrics.taskrun.level: task
    options: {}
    performance:
      disable-ha: false
    require-git-ssh-secret-known-hosts: false
    results-from: termination-message
    running-in-environment-with-injected-sidecars: true
    send-cloudevents-for-runs: false
    set-security-context: false
    trusted-resources-verification-no-match-policy: ignore
  platforms:
    openshift: {}
  profile: all
  pruner:
    disabled: false
    keep: 100
    resources:
      - pipelinerun
    schedule: 0 8 * * *
  result:
    disabled: false
    is_external_db: false
    options: {}
    performance:
      disable-ha: false
  targetNamespace: tekton-pipelines
  tektonpruner:
    disabled: true
    global-config:
      enforcedConfigLevel: global
      failedHistoryLimit: null
      historyLimit: 100
      namespaces: null
      successfulHistoryLimit: null
      ttlSecondsAfterFinished: null
    options: {}
  trigger:
    disabled: false
    enable-api-fields: stable
    options: {}
