global:
  domain: argocd.achaemenid.nl
  logging:
    format: json
    level: debug

server:
  replicas: 2
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    ingressClassName: "nginx"
    hostname: "argocd.achaemenid.nl"
    path: /
    pathType: Prefix
    tls: true

controller:
  replicas: 1

repoServer:
  replicas: 2

applicationSet:
  replicas: 2

redis-ha:
  enabled: true
  persistentVolume:
    enabled: false