# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "init"
#   createdAt: seconds:1771253037  nanos:61023733
#   expiresAt: seconds:1802789040
#   id:        d825db8b-538f-4018-b295-065cfde3f0b9
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDZjCCAk6gAwIBAgIJAJY3TCMmCHLfMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNjAyMTYxMzQ0
            MDBaFw0yNzAyMTYxNDQ0MDBaMIG8MS0wKwYDVQQKEyRkODI1ZGI4Yi01MzhmLTQw
            MTgtYjI5NS0wNjVjZmRlM2YwYjkxIjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9M
            X1NFUlZJQ0UxSDBGBgNVBAMMP0FETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAw
            MDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTA4
            MjQyMDM5NDMyNTM5MzA3MTkwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATvMIen
            42FljWGXEg4J+tLDdgGm6dJflxysLY0f9bJoSKwRzluGDBhErLXQ0hm4RKLoq/Az
            VHK74pUe9CEjH2kEo4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
            BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUrsbnnvV8
            0vMDQ9FHZeuhbQ72zicwHwYDVR0jBBgwFoAUUB1Wn4OWLvowwU0pQCzFeEwACjMw
            RQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lv
            bi1jb250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAFHecN/cf
            h6awt/SEDnQCp2dX/GddiCxYi9FzRYjfi9K7ry7sJDykjvbztPkv1jYm8/OlzZcs
            i6TaKYbb9oI9c4ifXx1SAxgymQpRt1VRaDYXIEYnCEWHzxi3eGA2DPGLjJSIPxMS
            JyEe845kXRcI2DU1HHF0HYXgStW6TJ5f7I8cjB1Lcn8BB47d2kSBNOQ31ViQPrXb
            cxKebjepPsNdaQFVhxMoKiJf4/U8aPiuXlR+t+IMyPwS9wWOsCQtD1mC32GcpEvS
            mLHZvHLnA3ipJL2IHKoXET5uBO6bHnAfJG94tBnOeJY3XivtV/CvdJSUxZrFxtOR
            HQm1TSjoPJxl7g==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIOwYS161M2nbkuZ6+ggC67k9FwJq8zXGatbQ8H0UgQBboAoGCCqGSM49
            AwEHoUQDQgAE7zCHp+NhZY1hlxIOCfrSw3YBpunSX5ccrC2NH/WyaEisEc5bhgwY
            RKy10NIZuESi6KvwM1Ryu+KVHvQhIx9pBA==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRAMCK6I9jBgWXf1QHRDtbZs4wDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2
        MDIxNjE0MzUxNVoXDTMxMDIxNTE0MzUxNVowKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEA3NytyZlS8Cw6ouofOg2SR1B/xG7yXxCaH8tu2h3e95kHvELrG+4h18m5
        jX554k0PyhJFDUzrdB7QyeWSpEtIQjZUE1eKIrsC4HTtZAYj9Xe9TJ+WLi5IE/Jz
        g1+vC+nImWy5MiOZbGuLoYQDn9eNJmjfo+Lw7GcJPhTShpZ26OSMtbBFdndU2vSX
        APsR/Vg80N02uAUSaRzoM50dKxJmsn2z7dut+cgWYaUXlUuJXA4zdl2i8Is4hBhs
        Krg/UAw7O4Tj5XW0mIAlwIrq8kgiy1PKRT8zk5EtL0Cn6JQZ9tmL6arYme6UjS8Y
        C6pBt9P8SZupTPRNzytF5CKhu+4I1QIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFFAdVp+Dli76MMFNKUAsxXhMAAozMA0GCSqGSIb3DQEBCwUAA4IB
        AQAag2LpYC+3HecRouoKAtoLVe5IoNM5ApgC5JR8c7wsbOYssNPamdfIX3k2a02E
        wqXLClp+X3kQOKcZZ9DU+dzbaiqlIwCGaFhBZEWxt/XY+k15CS/LC9ogJId3h2is
        ASaHoyPI8UBMqYw1a0Y0L5FZAa2bklo5dWbhf6WJp74Ijvao4yBfn6dof83vzk2m
        yAwH+ICBAx5voxMQo6BYeDi3fPjhVYwjccPLbjQsgRolQQFAgwLpWhMh4ezuvzPX
        7YMWOCzf5ou1wEFgo0QZV0E4CqnZbW3xBSeJktbV+EYMy10vagaijaCoe2rbriBu
        JV/nt55nPecKtwu8VYh20GWw
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIIcNG1ucihsnIwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2MDIxNjEzNDQw
            MFoXDTI3MDIxNjE0NDQwMFowgasxLTArBgNVBAoTJGQ4MjVkYjhiLTUzOGYtNDAx
            OC1iMjk1LTA2NWNmZGUzZjBiOTEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzgxMjk0Nzg2MTE5MjAwNzMzMzAw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR05Bwww5YCAlgI7v8HRVqWF+D1SC9G
            R0Fr0gHapXPklylmKysy30Y9JMdRti/kh/bsh1lyymZ+I7tPY8Sm/T1Po4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUrA+WbE7FknlBNaYG4q3HVB88T+IwHwYD
            VR0jBBgwFoAUUB1Wn4OWLvowwU0pQCzFeEwACjMwNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQDPBm+gZjdIa1MHdDeWxIiXwJH47bQIvuGPylawOz+U1UV9UN02DNoe
            jdXrv2YEx7+Dn7radmW5ciwoWYUQau5LQYRFuFd1D5I5+M4fSDy3J5zJ8M1Rw0o5
            YLmNdCsIswQAAvXIKznMjZtwwyaUXvcmAs4zNdlV6vr2XMfOLJwbBaAgjn6HVfPl
            ZOSQwaDq5VyVSVeSI90qBk3qYqiu+HWSWScpURI+Xm/5/aS1M5mRTt2Q3Le3h+/m
            ROcnukIGf5DwgZY+F8YmHV7EwBlvV69iRsLLuSsKunllI6vDCgYk2+5fkUvJD45b
            zF/huc9wDx44WrJFtUanaIYkHwSFHrYO
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIPCkGvEHP+bxkTHrgXqADEWh8dfighCkeYVpw+iH2vGFoAoGCCqGSM49
            AwEHoUQDQgAEdOQcMMOWAgJYCO7/B0Valhfg9UgvRkdBa9IB2qVz5JcpZisrMt9G
            PSTHUbYv5If27IdZcspmfiO7T2PEpv09Tw==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVTCCAj2gAwIBAgIIKVlG0vDbymYwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2MDIxNjEzNDQw
            MFoXDTI3MDIxNjE0NDQwMFowgaUxLTArBgNVBAoTJGQ4MjVkYjhiLTUzOGYtNDAx
            OC1iMjk1LTA2NWNmZGUzZjBiOTEXMBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7
            BgNVBAMMNFNFTlNPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0w
            MDAwMDAwMDAwMDAxHDAaBgNVBAUTEzI5Nzk0OTA1MDAyODAzMDYyNzgwWTATBgcq
            hkjOPQIBBggqhkjOPQMBBwNCAARR/M3Sr48+28wuY5KsS3fx1/3qsPnAOQzENZNA
            glBoYky/cv0tj6mAeFfiGmJZpoEnsZ6d2nCV23z7EM8VlVddo4HOMIHLMA4GA1Ud
            DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
            AQH/BAIwADAdBgNVHQ4EFgQUYCVgLw6W7aY3PNZqp1Jwse7y5WAwHwYDVR0jBBgw
            FoAUUB1Wn4OWLvowwU0pQCzFeEwACjMwTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNr
            cm94ghNzZW5zb3Iuc3RhY2tyb3guc3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3Jv
            eC5zdmMwDQYJKoZIhvcNAQELBQADggEBAK/NQ9cMePwHO/zV0f3Pa745K6o0ijPH
            PpFKu0w5/jNWkPOkhEvKlYqIWdyKdvJlyZVfWieoooJUNE52JPHanm8kH9DBvlcb
            OsIC2Ow3s1edSxWEtm/6jusZSShcOTEfIHuY4VB3YKV2iAjlEJ2LLTz//8kqogrt
            U6g7oIaY92RMWwcVK71Jp5XlWs8quJg+CP0hJBciLij3PTJ7wg+Qiewxt3X6d9FP
            S9vvDKUapo7uEZdfhuuhcZOTcDr9gI1GFxY6fiQXMJzkBCUPGcBhqa6UiGoE1JQj
            UmODrcUtARM5YZzFIWFjmO6rShVpaxLL17AVDlqQ8YuIoNnnCYYduh0=
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIJ6l4/9vTcWYV3EeIxZcNKTscCI//0658Kx6dHGaGlSYoAoGCCqGSM49
            AwEHoUQDQgAEUfzN0q+PPtvMLmOSrEt38df96rD5wDkMxDWTQIJQaGJMv3L9LY+p
            gHhX4hpiWaaBJ7Gendpwldt8+xDPFZVXXQ==
            -----END EC PRIVATE KEY-----
