# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "init-bundle"
#   createdAt: seconds:1771256699  nanos:869682542
#   expiresAt: seconds:1802792700
#   id:        0beca207-88e3-4ee8-a516-e133574db44c
#
admissionControl:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDYzCCAkugAwIBAgIIDFt1xi2BPlwwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2MDIxNjE0NDUw
            MFoXDTI3MDIxNjE1NDUwMFowgboxLTArBgNVBAoTJDBiZWNhMjA3LTg4ZTMtNGVl
            OC1hNTE2LWUxMzM1NzRkYjQ0YzEiMCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xf
            U0VSVklDRTFIMEYGA1UEAww/QURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAw
            MDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMRswGQYDVQQFExI4OTA0
            MzQ4NDUzNjMyMjQxNTYwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARUnCzE5NTq
            UlQjrHszx/RbditYE9lVpTL3WA5nMA8RFTF/Uy/NuZns/fM+xh2SIcXai+TVyTug
            UQh05sEYkMzFo4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF
            BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUuLqUgHAkNAXv
            x08ByGIwDQElq0cwHwYDVR0jBBgwFoAUomB7pXzQhmChynreFrD5N0Fw9MwwRQYD
            VR0RBD4wPIIaYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lvbi1j
            b250cm9sLnN0YWNrcm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAusXODJxe4jhK
            2Rmh47jUaF4gOXhk+VZS93cuCsuFr98rTkPHclGtMmEi46VGfnnzK35GyUZmi8pi
            J1ynbCbAOfAu+RaawDnlnyjM31YK25qBOiojZcKGUK361hwXnfAZi0ltZFUnKPA3
            O/ekzL0b/uWKlCOcxjNJV0XmEwVJEDaRJ7RiT6BFTmsyHNWVUXAvoLXGvOYm3lTD
            nh6rUN56VRcxpze3+kLmq4M02UPjoVFjxIF+QyazKle9+mL812F24KF5ER82fazU
            Ast0iG90mfLGLeTpbPv/JlM88UVj0z89WQnyMErECB1xxVdnQN5bdXeRhpKY8q+N
            d4yGOqUhpQ==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEICgtkgr6Qpre9bSveUe61iHXxdIt5vtSvRia+IdnD/zMoAoGCCqGSM49
            AwEHoUQDQgAEVJwsxOTU6lJUI6x7M8f0W3YrWBPZVaUy91gOZzAPERUxf1MvzbmZ
            7P3zPsYdkiHF2ovk1ck7oFEIdObBGJDMxQ==
            -----END EC PRIVATE KEY-----
ca:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDPjCCAiagAwIBAgIRAJoCluMdW1ped+Yoeofkui0wDQYJKoZIhvcNAQELBQAw
        KTEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2
        MDIxNjE1MzEwOVoXDTMxMDIxNTE1MzEwOVowKTEnMCUGA1UEAxMeU3RhY2tSb3gg
        Q2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEAvXiV9kqmrHUhnzQwLYttJZkeyTM7ojwp1xiDZ45krO3HPPMycReHXOk+
        HcuSuf0XvxvzxQNjD3gZd3dHuE0g7Tb+nE+VpXpCpsFwpJ1Rl/vaB0KOjvB+M0Ht
        GspZ5//CPeXH/XXtmAdhHxGuvvJbyt1JnTBvfBeKwCeBoo7Tvai6+RQ37aQtOHJW
        +efq9UqLp5D53btELjJR0Z4cLDsgehQOb4sfNA0ZYA7I3ortm2SGs4MkGSpFcchQ
        g4O4blz2Ho0W7Ohncd2mK2j42b3hLG8fw43y3EOD2e1ydHHWkD0xUJ7IHaDjCT7o
        KH+a3AKXD6Q+CkIiXsBBGGKfcjtSUQIDAQABo2EwXzAOBgNVHQ8BAf8EBAMCAqQw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
        HQYDVR0OBBYEFKJge6V80IZgocp63haw+TdBcPTMMA0GCSqGSIb3DQEBCwUAA4IB
        AQCbhT/hao1rjLdYmmYK9nlK6lL7Cnji0XToFKzpPTtjuXCKbzkn2SnxL+cgrf19
        tKy44jwYpLdtQ2mvgkwKQzSiDKKrCk0wh0DJoQp6dxUqjGRPQc4bIOQRwlncgEZP
        9q08f6KuQHmbU6pFQICgxpmBiRiYF9q0uFXBb8k5EL37FOnok1xPAVg3VMK/2nEw
        o0KoUTJN9Aoomlq+hQP9YsxavhONb/2oOu8hYTkwJrdXkuJPPY0STHbXoNxouLB6
        DPfIVQfXYTF2gUozLBa5QnJeKZ4IbRV054Ot8IefnXwG47/Q5cxiQCvGiLAMvVB3
        1KkHCKJX919HLtZhzzDk+Cde
        -----END CERTIFICATE-----
collector:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDRDCCAiygAwIBAgIIMQ0KaBvID1MwDQYJKoZIhvcNAQELBQAwKTEnMCUGA1UE
            AxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTI2MDIxNjE0NDUw
            MFoXDTI3MDIxNjE1NDUwMFowgasxLTArBgNVBAoTJDBiZWNhMjA3LTg4ZTMtNGVl
            OC1hNTE2LWUxMzM1NzRkYjQ0YzEaMBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0Ux
            QDA+BgNVBAMMN0NPTExFQ1RPUl9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAt
            MDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUTEzM1MzQ0OTI3MjQ4MTQ2Nzk4OTEw
            WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATOwrpHfXFOcjJUHDysbX3IYaoy8urt
            QcCBHVXeSewwRZ8L9DAIjToLghLv62S1vyzCwcULXGEPv+VExGoPfeqro4G3MIG0
            MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
            DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU2RqsYWQNRb/E3xDlpcELqQCxzeAwHwYD
            VR0jBBgwFoAUomB7pXzQhmChynreFrD5N0Fw9MwwNQYDVR0RBC4wLIISY29sbGVj
            dG9yLnN0YWNrcm94ghZjb2xsZWN0b3Iuc3RhY2tyb3guc3ZjMA0GCSqGSIb3DQEB
            CwUAA4IBAQAD5e6CS6y1qZRWvIvg94nz2tdWIbhkeufYUjEJt7/R82VkiEQ80uUT
            wiq1TnC3w1BvVz+2Ouj9Zo1HaLSLPAkjFoSzHIPLnrYN2PVDdlFkfXbF/1vUEpHz
            Gyn3DGFYuC7Nuhc+rceEU8p0O3RZgCbsO/gcgpaqvYvasVsF44rPQtDhh8R/nxlH
            8Ms9yeJXwFqQvrUfqMuHz54b5DzYfBU0Dcv2aULkCO7yKJOB+YnACGv09hd700dG
            OF4hgFkiYrUuSYAEKOGaLl7sGoME7deaYSnB0Y+IE6ze4EIYyGRd+COrw+COE4+2
            Qm0wSBF/kmnX+7mho9g1BH3p890uMTKa
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIMVoXv6umM2JaYDDE0WBK8W9+bSw99dhg1vLzjBSFRl0oAoGCCqGSM49
            AwEHoUQDQgAEzsK6R31xTnIyVBw8rG19yGGqMvLq7UHAgR1V3knsMEWfC/QwCI06
            C4IS7+tktb8swsHFC1xhD7/lRMRqD33qqw==
            -----END EC PRIVATE KEY-----
sensor:
    serviceTLS:
        cert: |
            -----BEGIN CERTIFICATE-----
            MIIDVzCCAj+gAwIBAgIJAOPujArpb2DHMA0GCSqGSIb3DQEBCwUAMCkxJzAlBgNV
            BAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNjAyMTYxNDQ1
            MDBaFw0yNzAyMTYxNTQ1MDBaMIGmMS0wKwYDVQQKEyQwYmVjYTIwNy04OGUzLTRl
            ZTgtYTUxNi1lMTMzNTc0ZGI0NGMxFzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0w
            OwYDVQQDDDRTRU5TT1JfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
            MDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxNjQyNDIxODg2OTU2MDcyOTc5OTBZMBMG
            ByqGSM49AgEGCCqGSM49AwEHA0IABGtqes2oU5T2d1uel9kH1oX5k9j/uepa0w9v
            whHDFOGzmZjGlTXIZM89fVWNcnSsJ9amMQXVEEod3pYJpeCOKOqjgc4wgcswDgYD
            VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
            HRMBAf8EAjAAMB0GA1UdDgQWBBQj7kcyKsoH/PaW6uKF7sN6yqJ6cTAfBgNVHSME
            GDAWgBSiYHulfNCGYKHKet4WsPk3QXD0zDBMBgNVHREERTBDgg9zZW5zb3Iuc3Rh
            Y2tyb3iCE3NlbnNvci5zdGFja3JveC5zdmOCG3NlbnNvci13ZWJob29rLnN0YWNr
            cm94LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAk63zD8QMd9JAUZ9exFtkQwiwtEgK
            YnAyCIjrqUnZ4vLw4KB7VtsMOcTmDryULjaW8on1ZnK2a4yZYFpTMXnEJSvXa2pg
            nLBvrGYAc2FXrRLOGaPKCvVvYt/gbC/7OqgzYHRXVTq9CQ8UZf8PL/LqH4vZLU5M
            ATumLI0R2rJDRQIpq42eLKWCgJxhX/KxkIyWg45hIkJe/Qfi2mcjYwiN5ucCwRF3
            CNdt7X3HN8wlgNxdzL/XuV5CncnrHagt3M0UmLt9s/7f8RomiqZv0lbcd6K6u53W
            iIm5p3gIInbEBevSLJNLrWPdEmrT+UO+gP3EQGVmJfM6myaK80dh3rEJCg==
            -----END CERTIFICATE-----
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIBsm6VoI5zn9PYEveFKwfU9+lAS2qPi83Hd4duBRQ22roAoGCCqGSM49
            AwEHoUQDQgAEa2p6zahTlPZ3W56X2QfWhfmT2P+56lrTD2/CEcMU4bOZmMaVNchk
            zz19VY1ydKwn1qYxBdUQSh3elgml4I4o6g==
            -----END EC PRIVATE KEY-----
