apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-metrics
  namespace: collectors
data:
  config.alloy: |
    logging {
      level  = "debug"
    }

    discovery.kubernetes "k8s_pods" {
      role = "pod"
      selectors {
        role = "pod"
        field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname)
        label = "scrape=true"
      }
    }

    discovery.relabel "pod_metrics" {
      targets = discovery.kubernetes.k8s_pods.targets

      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        action = "replace"
        target_label = "pod_name"
      }
      
      rule {
        source_labels = ["__meta_kubernetes_pod_annotaions_metrics_path"]
        target_label  = "__metrics_path__"
        regex         = "(.+)"
        action        = "replace"
      }
    }

    prometheus.scrape "pod_metrics" {
      targets    = discovery.relabel.pod_metrics.output
      forward_to = [prometheus.remote_write.local.receiver]
      scrape_interval = "30s"
    }

    prometheus.remote_write "local" {
        endpoint {
            url = "http://mimir-distributed-gateway.monitoring/api/v1/push"
        }
    }