apiVersion: v1
kind: ConfigMap
metadata:
  name: external-alloy
  namespace: collectors
data:
  config.alloy: |
    discovery.file "external" {
      files = ["/etc/alloy/external/*.yaml"]
    }

    discovery.relabel "keep_filepath" {
      targets = discovery.file.external.targets
      rule {
        source_labels = ["__meta_filepath"]
        target_label = "filepath"
      }
    }

    prometheus.scrape "default" {
      targets    = discovery.relabel.keep_filepath.output
      forward_to = [prometheus.remote_write.demo.receiver]
      scrape_interval = "15s"
      metrics_path = "/metrics"
      scheme = "https"
    }

    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir.example.com/api/v1/push"
      }
    }