# Get Tenant ID
# az account list --output table

# Get client ID
#terraform output -json oidc_applications | jq -r '.gitlab.client_id'

# Get client secret
#terraform output -json oidc_client_secrets | jq -r '.gitlab'

# Get full OIDC config
#terraform output oidc_config
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-oidc-secret
  namespace: gitlab  # Your GitLab namespace
type: Opaque
stringData:
  provider: |
    name: openid_connect
    label: "Azure AD"
    icon: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Microsoft_Azure_Logo.svg"
    args:
      name: openid_connect
      scope:
        - openid
        - profile
        - email
      response_type: code
      issuer: https://login.microsoftonline.com/<TENANT_ID>/v2.0
      discovery: true
      client_auth_method: query
      uid_field: preferred_username
      pkce: true
      client_options:
        identifier: "CLIENT_ID_HERE"
        secret: "CLIENT_SECRET_HERE"
        redirect_uri: "https://GITLAB_ADDRESS/users/auth/openid_connect/callback"