apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---  
apiVersion: v1
kind: Secret
metadata:
  name: openldap-secrets
  namespace: openldap
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: <>
  LDAP_CONFIG_ADMIN_PASSWORD: <>
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pla
  namespace: openldap
spec:
  parentRefs:
    - name: public-gw
      namespace: kgateway-system
  hostnames:
    - pla.achaemenid.nl
  rules:
  - backendRefs:
    - name: phpldapadmin
      port: 8080