apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---  
apiVersion: v1
kind: Secret
metadata:
  name: openldap-secrets
  namespace: openldap
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: <>
  LDAP_CONFIG_ADMIN_PASSWORD: <>
