apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---  
apiVersion: v1
kind: Secret
metadata:
  name: openldap-secrets
  namespace: openldap
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: <>
  LDAP_CONFIG_ADMIN_PASSWORD: <>
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pla
  namespace: openldap
spec:
  parentRefs:
    - name: public-gw
      namespace: kgateway-system
  hostnames:
    - pla.achaemenid.nl
  rules:
  - backendRefs:
    - name: phpldapadmin
      port: 8080
---
# ldapsearch -Y EXTERNAL -H ldapi:/// \
#   -b "dc=achaemenid,dc=nl" \
#   "(objectClass=inetOrgPerson)" \
#   dn uid cn mail


# slappasswd


# slappasswd
# New password: 
# Re-enter new password: 
# {SSHA}m9Y7OQ7t5u/abmz4nDBaQKWD1/2wb4sk


# cat > admin-user.ldif <<EOF
# dn: cn=admin,dc=achaemenid,dc=nl
# objectClass: inetOrgPerson
# objectClass: simpleSecurityObject
# objectClass: posixAccount
# cn: admin
# sn: admin
# uid: admin
# uidNumber: 9999
# gidNumber: 9999
# homeDirectory: /home/admin
# loginShell: /bin/bash
# userPassword: {SSHA}m9Y7OQ7t5u/abmz4nDBaQKWD1/2wb4sk
# mail: admin@achaemenid.nl
# EOF

# ldapadd -Y EXTERNAL -H ldapi:/// -f admin-user.ldif

# login:
# admin
# password


# # check with TCPRoute
# ldapsearch -H ldap://91.98.0.225:389 -D "cn=admin,dc=achaemenid,dc=nl" -W -b "dc=achaemenid,dc=nl"  "(objectClass=inetOrgPerson)" dn uid cn mail