apiVersion: v1
kind: Secret
metadata:
  name: postgresql-creds
  namespace: vault
type: Opaque
stringData:
  password: ""
  repmgr-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: pgpool-creds
  namespace: vault
type: Opaque
stringData:
  admin-password: ""