apiVersion: v1
kind: Secret
metadata:
  name: postgresql-creds
  namespace: vault
type: Opaque
stringData:
  password: ""
  repmgr-password: ""
  postgres-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: pgpool-creds
  namespace: vault
type: Opaque
stringData:
  admin-password: ""

## Login to vault DB with these credential:
## PGPOOL_POSTGRES_PASSWORD : "" vautusername
## PGPOOL_POSTGRES_USERNAME : "" vaultpassword
## PGPOOL_SR_CHECK_DATABASE : postgres