apiVersion: v1
kind: Secret
metadata:
  name: postgresql-creds
  namespace: vault
type: Opaque
stringData:
  username: ""
  password: ""
  database: ""
  repmgr-username: ""
  repmgr-password: ""
  repmgr-database: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: pgpool-creds
  namespace: vault
type: Opaque
stringData:
  admin-username: ""
  admin-password: ""