apiVersion: v1
kind: Secret
metadata:
  name: vault-storage-config
  namespace: vault
type: Opaque
stringData:
  config.hcl: |
    storage "postgresql" {
    connection_url = "postgres://vault:pass@ip:5432/vault"
    ha_enabled = "true"
    ha_table = "vault_ha_locks"
    }