apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-external
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/kaviankarimzadeh
      targetRevision: 0.3.2
      chart: alloy
      helm:
        releaseName: alloy-external
        valueFiles:
        - values.yaml
        - $values/values/alloy-external.yaml
    - repoURL: 'https://github.com/kaviankarimzadeh/argocd-apps.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: collectors
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true
