apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-logs
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/kaviankarimzadeh
      targetRevision: 1.1.2
      chart: alloy
      helm:
        releaseName: alloy-logs
        valueFiles:
        - values.yaml
        - $values/values/alloy-logs.yaml
    - repoURL: 'https://github.com/kaviankarimzadeh/argocd-apps.git'
      targetRevision: main
      ref: values
    - repoURL: 'https://github.com/kaviankarimzadeh/argocd-apps.git'
      targetRevision: main
      path: ./k8s-stuff/alloy/logs
  destination:
    server: https://kubernetes.default.svc
    namespace: collectors
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true
