apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-metrics
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/kaviankarimzadeh
      targetRevision: 0.10.1
      chart: alloy
      helm:
        releaseName: alloy-metrics
        valueFiles:
        - values.yaml
        - $values/values/alloy-metrics.yaml
    - repoURL: 'https://github.com/kaviankarimzadeh/argocd-apps.git'
      targetRevision: main
      ref: values
    - repoURL: 'https://github.com/kaviankarimzadeh/argocd-apps.git'
      targetRevision: main
      path: ./k8s-stuff/alloy/metrics
  destination:
    server: https://kubernetes.default.svc
    namespace: collectors
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true
