apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/kaviankarimzadeh
      targetRevision: 1.19.2
      chart: cilium
      helm:
        releaseName: cilium
        valueFiles:
        - values.yaml
        - $values/values/cilium.yaml
    - repoURL: 'https://github.com/kaviankarimzadeh/argocd-apps.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: null
