apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway-crds-helm
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/kaviankarimzadeh
      targetRevision: v2.1.1
      chart: kgateway-crds
      helm:
        skipCrds: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kgateway-system
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true
