apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway-helm
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/kaviankarimzadeh
      targetRevision: v2.1.1
      chart: kgateway
      helm:
        releaseName: kgateway
        valueFiles:
        - values.yaml
        - $values/values/kgateway-helm.yaml
    - repoURL: 'https://github.com/kaviankarimzadeh/argocd-apps.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kgateway-system
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true
