apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/kaviankarimzadeh
      targetRevision: 4.3.1
      chart: kube-state-metrics
      helm:
        releaseName: kube-state-metrics
        valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true
