apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/kaviankarimzadeh
      targetRevision: 6.3.0
      chart: kube-state-metrics
      helm:
        releaseName: kube-state-metrics
        valueFiles:
        - values.yaml
        - $values/values/kube-state-metrics.yaml
    - repoURL: 'https://github.com/kaviankarimzadeh/argocd-apps.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true
