apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir-distributed
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/kaviankarimzadeh
      targetRevision: 5.3.0
      chart: mimir-distributed
      helm:
        releaseName: mimir-distributed
        valueFiles:
        - values.yaml
        - $values/values/mimir-distributed.yaml
    - repoURL: 'https://github.com/kaviankarimzadeh/argocd-apps.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true
