apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/kaviankarimzadeh
      targetRevision: v1.17.5
      chart: rook-ceph-cluster
      helm:
        parameters:
        - name: 'csi.enableCephfsDriver'
          value: 'false'
        - name: 'csi.enableMetadata'
          value: 'true'
        releaseName: rook-ceph-cluster
        valueFiles:
        - values.yaml
        - $values/values/rook-ceph-cluster.yaml
    - repoURL: 'https://github.com/kaviankarimzadeh/argocd-apps.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true
